# permissions for end users to edit boshdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boshdeployment-editor-role
rules:
- apiGroups:
  - bosh.gluon.starkandwayne.com
  resources:
  - boshdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bosh.gluon.starkandwayne.com
  resources:
  - boshdeployments/status
  verbs:
  - get
