
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gluon.starkandwayne.com
  resources:
  - boshconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gluon.starkandwayne.com
  resources:
  - boshconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gluon.starkandwayne.com
  resources:
  - boshdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gluon.starkandwayne.com
  resources:
  - boshdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gluon.starkandwayne.com
  resources:
  - boshstemcells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gluon.starkandwayne.com
  resources:
  - boshstemcells/status
  verbs:
  - get
  - patch
  - update
